remote_theme: pages-themes/cayman@v0.2.0
title: SQL Projects by Phạm Lê Ngọc Sơn
description: A collection of database design projects and SQL implementations by Phạm Lê Ngọc Sơn. Includes designs for various systems like hospital management, railway systems, and library management. All SQL queries are written for PostgreSQL database.
